# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By


class TestFirsttest:
    def setup_method(self, method):
        # self.driver = webdriver.Firefox(service=FirefoxService(GeckoDriverManager().install()))
        # self.driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_firsttest(self):
        self.driver.get("https://rozetka.com.ua/")
        self.driver.set_window_size(1472, 1028)
        self.driver.find_element(By.NAME, "search").click()
        self.driver.find_element(By.CSS_SELECTOR, ".search-suggest__item-text_type_nowrap").click()
        element = self.driver.find_element(By.CSS_SELECTOR,
                                           ".catalog-grid__cell:nth-child(6) .ng-lazyloaded:nth-child(1)")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".checkbox-filter__item:nth-child(4) > .checkbox-filter__link").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".sidebar-block:nth-child(3) > .sidebar-block__toggle")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        elements = self.driver.find_elements(By.CSS_SELECTOR, ".catalog-grid__cell:nth-child(3) .goods-tile__title")
        assert len(elements) > 0
        element = self.driver.find_element(By.CSS_SELECTOR, ".content")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).click_and_hold().perform()
        element = self.driver.find_element(By.CSS_SELECTOR, ".content")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, ".content")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).release().perform()
        self.driver.find_element(By.CSS_SELECTOR, ".content").click()
        self.driver.close()
